#!/usr/bin/env bash

#A script that transfers a file from our client to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/.
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/.
fi
