#!/usr/bin/env bash
#A script that install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
