#!/usr/bin/env bash

#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

let k=1

while ((k < 11))
do
        if (( k == 4 ))
        then
                echo "bad luck"
                (( k++))
        elif (( k == 8 ))
        then
                echo "good luck"
                (( k++ ))
        else
                echo "Best school"
                (( k++ ))
        fi
done
