#!/usr/bin/env bash
# A script that installs and configures an apache2 web server to listen to port 8080
sudo apt update
sudo apt install apache2
service apache2 start
sudo echo "Listen 8080" >> /etc/apache2/ports.conf
sudo echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart
